---
openapi: 3.0.0
info:
  title: Bit Explorer API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/enecuum/BitExplorerAPI/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://bit.enecuum.com/api/v1
  description: Enecuum BIT Network. New API is first deployed here.
paths:
  /network_info:
    get:
      tags:
      - General
      summary: Retrieves network information
      description: Returns network info
      responses:
        "200":
          description: Successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
  /tps:
    get:
      tags:
      - General
      summary: Returns TPS (transactions per second) value
      responses:
        "200":
          description: Successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
  /get_token_holder_count:
    get:
      tags:
      - General
      summary: Returns the amount of accounts that hold the specified token. If no token is specified, it returns the amount of accounts that hold the native token (BIT)
      parameters:
      - name: hash
        in: query
        description: Token hash.
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: The amount of token holders.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
  /get_tokens_count:
    get:
      tags:
      - General
      summary: Returns the number of tokens deployed on the network and the breakdown of those tokens by type.
      responses:
        "200":
          description: The number of tokens and their breakdown by type.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
  /get_tickers_all:
    get:
      tags:
      - General
      summary: Returns the list of all token tickers on the network, including token hashes and captions.
      responses:
        "200":
          description: The list of all token tickers on the network, including token hashes and captions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
  /get_transfer_lock:
    get:
      tags:
      - General
      summary: Returns transfer lock value for the network
      responses:
        "200":
          description: The number of blocks required to be created on the network before the undelegation request can be satisfied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
  /token_info:
    get:
      tags:
      - General
      summary: Returns token info by hash.
      parameters:
      - name: hash
        in: query
        description: Token hash.
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Token info.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
  /native_token:
    get:
      tags:
      - General
      summary: Returns token info about the native token of the network.
      responses:
        "200":
          description: Token info.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
  /get_token_info_page:
    get:
      tags:
      - General
      summary: Returns the properties of the tokens listed on a specific BIT Explorer page. If no page number is specified, the amount of tokens to be displayed on a page and the total number of token info pages are returned.
      parameters:
      - name: page
        in: query
        description: Page number.
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Properties of the tokens listed on the specified page.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
components:
  schemas:
    inline_response_200:
      properties:
        target_speed:
          type: integer
          description: desired interval between block release in seconds
          example: 15
        reward_ratio:
          type: object
          properties:
            pos:
              type: integer
              description: Reward ratio for PoS nodes
              example: 5500
            poa:
              type: integer
              description: Reward ratio for PoA nodes
              example: 3181
            pow:
              type: integer
              description: Reward ratio for PoW nodes
              example: 500
            ref:
              type: integer
              description: Reward ratio for referrals
              example: 819
          description: Shares of the native token block reward by node types (10,000 = 100%)
        transfer_lock:
          type: integer
          description: Minimal amount of blocks between undelegation and transfer so that the transfer is valid
          example: 5
        pos_min_stake:
          type: integer
          description: Minimal stake for a PoS node
          example: 25000000000
        native_token:
          type: object
          properties:
            hash:
              type: string
              description: Native token hash
              example: "1"
            owner:
              type: string
              description: Address of the wallet that created the native token
              example: 029dd222eeddd5c3340e8d46ae0a22e2c8e301bfee4903bcf8c899766c8ceb3a7d
            fee_type:
              type: integer
              description: Fee type (see comment below, TO BE CLARIFIED - see comment below)
              example: 0
            fee_value:
              type: integer
              description: Fee value
              example: 1000000000
            ticker:
              type: string
              description: Native token ticker
              example: BIT
            decimals:
              type: integer
              description: Number of decimal places
              example: 10
            total_supply:
              type: string
              description: Total supply of native tokens
              example: "2455559059822244864"
            caption:
              type: string
              description: Token name
              example: Enecuum Testnet BIT
            active:
              type: integer
              description: TO BE EXPLAINED
              example: 0
            reissuable:
              type: integer
              description: (1 stands for tokens that can be minted and burned?)
              example: 0
            minable:
              type: integer
              description: Whether a token can be mined or not
              example: 1
            max_supply:
              type: integer
              description: Maximum token supply
              example: 3500000000000000000
            block_reward:
              type: integer
              description: Reward for the mining of a block
              example: 30460000000
            min_stake:
              type: integer
              description: The minimal stake for a PoS node
              example: 250000000000
            referrer_stake:
              type: integer
              description: TO BE EXPLAINED
              example: 10000000000000
            ref_share:
              type: integer
              description: TO BE EXPLAINED
              example: 2574
            txs_count:
              type: integer
              description: (TO BE CLARIFIED) amount of transactions with this token
              example: 6406044
            cg_price_usd:
              type: integer
              description: CoinGecko price of the token in USDT? (TO BE CLARIFIED)
            dex_price_usd:
              type: integer
              description: Price of the token on pour DEX (ENEX? TO BE CLARIFIED)
            price_raw:
              type: object
              properties:
                cg_price:
                  type: integer
                  description: CoinGecko price, different representation
                  example: 395275300
                dex_price:
                  type: integer
                  description: Our DEX price, different representation
                  example: 395275300
                decimals:
                  type: integer
                  description: Number of decimal places
                  example: 10
              description: a different representation of cg_price_usd and dex_price_usd
          description: Native token properties
        origin:
          type: object
          properties:
            publisher:
              type: string
              description: TO BE EXPLAINED
              example: 029dd222eeddd5c3340e8d46ae0a22e2c8e301bfee4903bcf8c899766c8ceb3a7d
            reward:
              type: integer
              description: TO BE EXPLAINED
              example: 2449913938434801029
            hash:
              type: string
              description: TO BE EXPLAINED
              example: BITGENESIS
            link:
              type: string
              description: TO BE EXPLAINED
              example: BITGENESIS
            sprout:
              type: string
              description: TO BE EXPLAINED
              example: BITGENESIS
            time:
              type: integer
              description: TO BE EXPLAINED
              example: 0
          description: TO BE EXPLAINED
        fee_shares:
          type: object
          properties:
            gen_share:
              type: integer
              description: TO BE EXPLAINED
              example: 300
            pow_share:
              type: integer
              description: TO BE EXPLAINED
              example: 50
            ldr_share:
              type: integer
              description: TO BE EXPLAINED
              example: 50
            pos_share:
              type: integer
              description: TO BE EXPLAINED
              example: 9600
          description: TO BE EXPLAINED
        MPK:
          type: object
          properties:
            x:
              type: integer
              description: TO BE EXPLAINED
            y:
              type: integer
              description: TO BE EXPLAINED
          description: TO BE EXPLAINED
        mblock_slots:
          type: object
          properties:
            size:
              type: integer
              description: TO BE EXPLAINED
              example: 2
            count:
              type: integer
              description: TO BE EXPLAINED
              example: 2
            min_stake:
              type: integer
              description: TO BE EXPLAINED - minimal stake
              example: 5000000000000000
          description: TO BE EXPLAINED
        dex:
          type: object
          properties:
            DEX_COMMANDER_ADDRESS:
              type: string
              description: TO BE EXPLAINED
              example: "21521491664182905476008420879569141998065218666733832615643"
            DEX_BURN_ADDRESS:
              type: string
              description: TO BE EXPLAINED
              example: 02dead000000000000000000000000000000000000000000000000000000000000
            DEX_ENX_TOKEN_HASH:
              type: string
              description: TO BE EXPLAINED
              example: 824e7b171c01e971337c1b25a055023dd53c003d4aa5aa8b58a503d7c622651e
            DEX_SPACE_STATION_ID:
              type: string
              description: TO BE EXPLAINED
              example: 50789932e52d80ff65a56547274498d865ce1d85f14bbacdcd5b575191f87621
            DEX_COMMANDER_FEE:
              type: integer
              description: TO BE EXPLAINED
              example: 5
            DEX_POOL_FEE:
              type: integer
              description: TO BE EXPLAINED
              example: 30
            DEX_TRUSTED_TOKENS:
              type: string
              description: TO BE EXPLAINED
              example: 824e7b171c01e971337c1b25a055023dd53c003d4aa5aa8b58a503d7c622651e
          description: TO BE EXPLAINED
    inline_response_200_1:
      properties:
        tps:
          type: integer
          description: Average rounded aount of transactions during the last 300 seconds
          example: 1
    inline_response_200_2:
      properties:
        count:
          type: integer
          description: The amount of token holding accounts
          example: 34676
    inline_response_200_3:
      properties:
        count:
          type: integer
          description: The total number of tokens deployed on the network.
          example: 1427
        non_reissuable:
          type: integer
          description: The number of non-reissuable tokens.
          example: 873
        reissuable:
          type: integer
          description: The number of reissuable tokens.
          example: 279
        minable:
          type: integer
          description: The number of minable tokens.
          example: 275
    inline_response_200_4:
      properties:
        hash:
          type: string
          description: Token hash.
          example: "1"
        ticker:
          type: string
          description: Token ticker.
          example: BIT
        caption:
          type: string
          description: Token caption (long name).
          example: Enecuum testnet BIT
    inline_response_200_5:
      properties:
        transfer_lock:
          type: integer
          description: Transfer lock value.
          example: 5
    inline_response_200_6:
      properties:
        hash:
          type: string
          description: Token hash
          example: "1"
        owner:
          type: string
          description: Address of the account that created the token
          example: 029dd222eeddd5c3340e8d46ae0a22e2c8e301bfee4903bcf8c899766c8ceb3a7d
        fee_type:
          type: integer
          description: Fee type (see comment below, TO BE CLARIFIED - see comment below)
          example: 0
        fee_value:
          type: integer
          description: Fee value
          example: 1000000000
        fee_min:
          type: integer
          description: Minimal fee
          example: 1000000000
        ticker:
          type: string
          description: Token ticker
          example: BIT
        decimals:
          type: integer
          description: Number of decimal places
          example: 10
        total_supply:
          type: string
          description: Total supply of the token
          example: "2455559059822244864"
        caption:
          type: string
          description: Long token name
          example: Enecuum Testnet BIT
        active:
          type: integer
          description: TO BE EXPLAINED
          example: 0
        reissuable:
          type: integer
          description: Indicates whether the token is reissuable (can be minted and burned)
          example: 0
        minable:
          type: integer
          description: Indicates whether a token can be mined
          example: 1
        max_supply:
          type: integer
          description: Maximum token supply
          example: 3500000000000000000
        block_reward:
          type: integer
          description: Reward for the mining of a block
          example: 30460000000
        min_stake:
          type: integer
          description: Minimal stake for a PoS node
          example: 250000000000
        referrer_stake:
          type: integer
          description: TO BE EXPLAINED
          example: 10000000000000
        ref_share:
          type: integer
          description: TO BE EXPLAINED
          example: 2574
        txs_count:
          type: integer
          description: (TO BE CLARIFIED) Amount of transactions with this token
          example: 6406044
        cg_price_usd:
          type: integer
          description: CoinGecko price of the token in USD (TO BE CLARIFIED)
        dex_price_usd:
          type: integer
          description: Price of the token on pour DEX (ENEX? TO BE CLARIFIED)
        price_raw:
          type: object
          properties:
            cg_price:
              type: integer
              description: CoinGecko price, different representation
              example: 395275300
            dex_price:
              type: integer
              description: Our DEX price, different representation
              example: 395275300
            decimals:
              type: integer
              description: Number of decimal places
              example: 10
          description: another ("raw", without decimal point) representation of cg_price_usd and dex_price_usd
